<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFzxwotG\ktarila_ParameterValidatorBundle_Tests_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFzxwotG/ktarila_ParameterValidatorBundle_Tests_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerFzxwotG.legacy');

    return;
}

if (!\class_exists(ktarila_ParameterValidatorBundle_Tests_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerFzxwotG\ktarila_ParameterValidatorBundle_Tests_KernelTestDebugContainer::class, ktarila_ParameterValidatorBundle_Tests_KernelTestDebugContainer::class, false);
}

return new \ContainerFzxwotG\ktarila_ParameterValidatorBundle_Tests_KernelTestDebugContainer([
    'container.build_hash' => 'FzxwotG',
    'container.build_id' => '4cacf42b',
    'container.build_time' => 1685888136,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFzxwotG');
