<?php

namespace ContainerFzxwotG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTestControllerService extends ktarila_ParameterValidatorBundle_Tests_KernelTestDebugContainer
{
    /**
     * Gets the public 'ktarila\ParameterValidatorBundle\Tests\TestController\TestController' shared autowired service.
     *
     * @return \ktarila\ParameterValidatorBundle\Tests\TestController\TestController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 5).'/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/TestController/TestController.php';

        $container->services['ktarila\\ParameterValidatorBundle\\Tests\\TestController\\TestController'] = $instance = new \ktarila\ParameterValidatorBundle\Tests\TestController\TestController();

        $instance->setContainer((new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'http_kernel' => ['services', 'http_kernel', 'getHttpKernelService', false],
            'parameter_bag' => ['privates', 'parameter_bag', 'getParameterBagService', false],
            'request_stack' => ['services', 'request_stack', 'getRequestStackService', false],
            'router' => ['services', 'router', 'getRouterService', false],
        ], [
            'http_kernel' => '?',
            'parameter_bag' => '?',
            'request_stack' => '?',
            'router' => '?',
        ]))->withContext('ktarila\\ParameterValidatorBundle\\Tests\\TestController\\TestController', $container));

        return $instance;
    }
}
